// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { MapId, MapIdTableId } from "./tables/MapId.sol";
import { MapCreator, MapCreatorTableId } from "./tables/MapCreator.sol";
import { MapName, MapNameTableId } from "./tables/MapName.sol";
import { SquareCoordinates, SquareCoordinatesData, SquareCoordinatesTableId } from "./tables/SquareCoordinates.sol";
import { SquareStopQualification, SquareStopQualificationTableId } from "./tables/SquareStopQualification.sol";
import { SquareQuest, SquareQuestTableId } from "./tables/SquareQuest.sol";
import { SquareQuestPoint, SquareQuestPointTableId } from "./tables/SquareQuestPoint.sol";
import { SquareIconUrl, SquareIconUrlTableId } from "./tables/SquareIconUrl.sol";
import { SquareDescription, SquareDescriptionTableId } from "./tables/SquareDescription.sol";
import { SquareCreator, SquareCreatorTableId } from "./tables/SquareCreator.sol";
import { SquareCreatorEns, SquareCreatorEnsTableId } from "./tables/SquareCreatorEns.sol";
import { SquareCreatorIconUrl, SquareCreatorIconUrlTableId } from "./tables/SquareCreatorIconUrl.sol";
import { NextSquareCoordinates, NextSquareCoordinatesData, NextSquareCoordinatesTableId } from "./tables/NextSquareCoordinates.sol";
import { PlayerIsInMap, PlayerIsInMapTableId } from "./tables/PlayerIsInMap.sol";
import { PlayerEns, PlayerEnsTableId } from "./tables/PlayerEns.sol";
import { PlayerIconUrl, PlayerIconUrlTableId } from "./tables/PlayerIconUrl.sol";
import { PlayerMapId, PlayerMapIdTableId } from "./tables/PlayerMapId.sol";
import { PlayerCoordinates, PlayerCoordinatesData, PlayerCoordinatesTableId } from "./tables/PlayerCoordinates.sol";
import { PlayerPointBalance, PlayerPointBalanceTableId } from "./tables/PlayerPointBalance.sol";
import { PlayerQuest, PlayerQuestTableId } from "./tables/PlayerQuest.sol";
import { PlayerIsMovable, PlayerIsMovableTableId } from "./tables/PlayerIsMovable.sol";
import { Encounter, EncounterData, EncounterTableId } from "./tables/Encounter.sol";
import { EncounterTrigger, EncounterTriggerTableId } from "./tables/EncounterTrigger.sol";
import { Encounterable, EncounterableTableId } from "./tables/Encounterable.sol";
import { VeryMonMap, VeryMonMapTableId } from "./tables/VeryMonMap.sol";
import { MonsterCatchAttempt, MonsterCatchAttemptTableId } from "./tables/MonsterCatchAttempt.sol";
import { Monster, MonsterTableId } from "./tables/Monster.sol";
import { Movable, MovableTableId } from "./tables/Movable.sol";
import { Obstruction, ObstructionTableId } from "./tables/Obstruction.sol";
import { OwnedBy, OwnedByTableId } from "./tables/OwnedBy.sol";
import { VeryMonPlayer, VeryMonPlayerTableId } from "./tables/VeryMonPlayer.sol";
import { VeryMonPosition, VeryMonPositionTableId } from "./tables/VeryMonPosition.sol";
