// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IMapSystem {
  function CreateGameMap(uint32 _mapId, string memory _gameMapName) external;

  function CreateInitialSquare(uint32 _mapId) external;
}
