// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IPlayerInfoSystem {
  function PlayerInfoSet(string memory _playerEns, string memory _playerIconUrl) external;
}
