// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IPlaySystem {
  function MapJoin(uint32 _mapId) external;

  function AdvanceThroughSquare(uint32 _newX, uint32 _newY, address _PlayerQuest) external;

  function QuestCompletion(uint32 _questPoint) external;

  function MapExit() external;
}
