// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface ISquareSystem {
  function CreateSquare(
    uint32 _squareMapId,
    uint32 _createdX,
    uint32 _createdY,
    uint32 _prevX,
    uint32 _prevY,
    string memory _creatorEns,
    string memory _creatorIconUrl,
    string memory _squareIconUrl,
    string memory _squareDescription,
    address _squareStopQualification,
    address _squareQuest,
    uint32 _squareQuestPoint
  ) external;
}
