// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { IBaseWorld } from "@latticexyz/world/src/interfaces/IBaseWorld.sol";

import { IMapSystem } from "./IMapSystem.sol";
import { IPlayerInfoSystem } from "./IPlayerInfoSystem.sol";
import { IPlaySystem } from "./IPlaySystem.sol";
import { ISquareSystem } from "./ISquareSystem.sol";
import { IVeryMonEncounterSystem } from "./IVeryMonEncounterSystem.sol";
import { IVeryMonMapSystem } from "./IVeryMonMapSystem.sol";

/**
 * The IWorld interface includes all systems dynamically added to the World
 * during the deploy process.
 */
interface IWorld is
  IBaseWorld,
  IMapSystem,
  IPlayerInfoSystem,
  IPlaySystem,
  ISquareSystem,
  IVeryMonEncounterSystem,
  IVeryMonMapSystem
{

}
